# Generated by Django 5.0 on 2024-06-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_pret'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='rembourser',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pret',
            name='solde_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pret',
            name='solde_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
