# Generated by Django 5.0 on 2024-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_pret_rembourser_pret_solde_total_alter_pret_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='delais',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
